<?php include $config['VIEW_PATH'].'login'.DS.'header.phtml';?>
<body>
        <div class="loginform"  <?php if($fail) { echo 'style="height: 400px"'; }?> >
            <p class="title">SIGN IN</p>
            <?php if($fail) { echo '<p class="fail">Incorrect Username or Password!</p>'; }?>
            <form action="index.php" method="post">
                <input type="text" <?php if($fail) { echo 'style="border: 2px dashed red;"'; }?> name="user" placeholder="User" required autofocus/>
                <input type="password" <?php if($fail) { echo 'style="border: 2px dashed red;"'; }?> name="pass" placeholder="Password" required/>
                <input type="submit" value="Log In"/>
                <input type="hidden" name="pg_v" value="%cntl_login-control">
            </form>
            <a id="register">don't have account? Register!</a>
        </div>
    </body>
</html>